version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/airdb
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      FRONTEND_SUCCESS_URL: ${FRONTEND_SUCCESS_URL}
      FRONTEND_FAILURE_URL: ${FRONTEND_FAILURE_URL}
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_JWT_ISSUER: ${APP_JWT_ISSUER}
      APP_JWT_EXPIRES_MINUTES: ${APP_JWT_EXPIRES_MINUTES}
    depends_on:
      - mongo
    ports:
      - "8080:8080"

  frontend:
    build:
      context: frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongo_data: